export const species = [
  { Name: "Species", fillColor: "#3DD94A" },
  { Name: "Plants", Category: "Species" },
  { Name: "Fungi", Category: "Species" },
  { Name: "Lichens", Category: "Species" },
  { Name: "Animals", Category: "Species" },
  { Name: "Mosses", Category: "Plants" },
  { Name: "Ferns", Category: "Plants" },
  { Name: "Gymnosperms", Category: "Plants" },
  { Name: "Dicotyledens", Category: "Plants" },
  { Name: "Monocotyledens", Category: "Plants" },
  { Name: "Invertebrates", Category: "Animals" },
  { Name: "Vertebrates", Category: "Animals" },
  { Name: "Insects", Category: "Invertebrates" },
  { Name: "Molluscs", Category: "Invertebrates" },
  { Name: "Crustaceans", Category: "Invertebrates" },
  { Name: "Others", Category: "Invertebrates" },
  { Name: "Fish", Category: "Vertebrates" },
  { Name: "Amphibians", Category: "Vertebrates" },
  { Name: "Reptiles", Category: "Vertebrates" },
  { Name: "Birds", Category: "Vertebrates" },
  { Name: "Mammals", Category: "Vertebrates" },
];
export const organizationTree = [
  { Id: "parent", Role: "University President", color: "#822B86" },
  { Id: "1", Role: "Chancellor", Supervision: "parent", color: "#3c418B" },
  { Id: "2", Role: "Vice President", Supervision: "parent", color: "#3c418B" },
  {
    Id: "3",
    Role: "Student Affairs",
    Supervision: "2",
    ChartType: "left",
    color: "#3c418B",
  },
  { Id: "4", Role: "Admin & Finance", Supervision: "2", color: "#3c418B" },
  { Id: "5", Role: "Academics", Supervision: "2", color: "#3c418B" },
  {
    Id: "6",
    Role: "External Relations",
    Supervision: "2",
    ChartType: "right",
    color: "#3c418B",
  },
  {
    Id: "7",
    Role: "Activities and Special events",
    Supervision: "3",
    color: "#267011",
  },
  {
    Id: "8",
    Role: "Educational Service Center",
    Supervision: "3",
    color: "#267011",
  },
  { Id: "9", Role: "Health Care", Supervision: "3", color: "#267011" },
  {
    Id: "10",
    Role: "Housing and Food Service Center",
    Supervision: "3",
    color: "#267011",
  },
  {
    Id: "11",
    Role: "Students Development",
    Supervision: "3",
    color: "#267011",
  },
  { Id: "13", Role: "General Maintenance", Supervision: "4", color: "#267011" },
  { Id: "14", Role: "Budget and Audit", Supervision: "4", color: "#71AF17" },
  { Id: "15", Role: "Human Resource", Supervision: "4", color: "#267011" },
  {
    Id: "16",
    Role: "Information Technology",
    Supervision: "4",
    color: "#71AF17",
  },
  {
    Id: "17",
    Role: "Facilities Management",
    Supervision: "4",
    color: "#267011",
  },
  {
    Id: "117",
    Role: "Environment Maintenance",
    Supervision: "4",
    color: "#71AF17",
  },
  { Id: "217", Role: "Custodial Service", Supervision: "4", color: "#267011" },
  { Id: "18", Role: "Faculties", Supervision: "5", color: "#267011" },
  { Id: "19", Role: "Educational Service", Supervision: "5", color: "#71AF17" },
  { Id: "20", Role: "University Library", Supervision: "5", color: "#267011" },
  { Id: "21", Role: "Center for Planning", Supervision: "5", color: "#71AF17" },
  { Id: "22", Role: "Summer Session", Supervision: "5", color: "#267011" },
  { Id: "23", Role: "Fund Development", Supervision: "6", color: "#71AF17" },
  { Id: "24", Role: "Admission", Supervision: "6", color: "#71AF17" },
  { Id: "25", Role: "Alumini Relations", Supervision: "6", color: "#71AF17" },
  {
    Id: "12",
    Role: "Recruitment & Promotion",
    Supervision: "6",
    color: "#71AF17",
  },
];
export const radialTree = [
  {
    Id: "parent",
    Name: "TVS",
    Designation: "Managing Director",
  },
  {
    Id: 1,
    Name: " Motor Cycles",
    Designation: "Project Manager",
    ReportingPerson: "parent",
  },
  {
    Id: 2,
    Name: "Scooter",
    Designation: "Project Manager",
    ReportingPerson: "parent",
  },
  {
    Id: 3,
    Name: "Mopeds",
    Designation: "Project Manager",
    ReportingPerson: "parent",
  },
  {
    Id: 4,
    Name: "Electric",
    Designation: "Project Manager",
    ReportingPerson: "parent",
  },
  {
    Id: 9,
    Name: "TVS IQube",

    ReportingPerson: 4,
  },
  {
    Id: 23,
    Name: "TVS IQube",

    ReportingPerson: 9,
  },
  {
    Id: 24,
    Name: "TVS IQube S",

    ReportingPerson: 9,
  },
  {
    Id: 25,
    Name: "TVS IQube ST",
    ReportingPerson: 9,
  },
  {
    Id: 26,
    Name: "TVS Apache RR 310",
    ReportingPerson: 1,
  },
  {
    Id: 10,
    Name: "TVS Ronin",
    ReportingPerson: 1,
  },
  {
    Id: 11,
    Name: "TVS Raider",
    ReportingPerson: 1,
  },
  {
    Id: 12,
    Name: "TVS RTR 165",
    ReportingPerson: 1,
  },
  {
    Id: 13,
    Name: "TVS Star City",
    ReportingPerson: 1,
  },
  {
    Id: 14,
    Name: "TVS Sport",
    ReportingPerson: 1,
  },
  {
    Id: 50,
    Name: "TVS Xl 100",
    ReportingPerson: 3,
  },
  {
    Id: 51,
    Name: "TVS Jupiter",
    ReportingPerson: 2,
  },
  {
    Id: 52,
    Name: "TVS Jupiter",
    ReportingPerson: 51,
  },
  {
    Id: 53,
    Name: "TVS Jupiter 125",
    ReportingPerson: 51,
  },
  {
    Id: 55,
    Name: "TVS Ntorq",
    ReportingPerson: 2,
  },
  {
    Id: 56,
    Name: "TVS Zest",
    ReportingPerson: 2,
  },
  {
    Id: 58,
    Name: "TVS Scooty Pep",
    ReportingPerson: 2,
  },
];

export const artificialIntelligence = [
  { Name: "Artificial Intelligence", fillColor: "#916DAF", branch: "root" },
  { Name: "Machine Learning", Category: "Artificial Intelligence" },
  {
    Name: "Natural Language Processing (NLP)",
    Category: "Artificial Intelligence",
  },
  { Name: "Speech", Category: "Artificial Intelligence" },
  {
    Name: "Planning, Scheduling, and Optimization",
    Category: "Artificial Intelligence",
  },
  { Name: "Robotics", Category: "Artificial Intelligence" },
  { Name: "Vision", Category: "Artificial Intelligence" },
  { Name: " Deep Learning ", Category: "Machine Learning" },
  { Name: "Predictive Analytics ", Category: "Machine Learning" },
  { Name: "Translation ", Category: "Natural Language Processing (NLP)" },
  { Name: "Classification", Category: "Natural Language Processing (NLP)" },
  {
    Name: "Information Extraction",
    Category: "Natural Language Processing (NLP)",
  },
  { Name: "Speech to Text", Category: "Speech" },
  { Name: "Text to Speech", Category: "Speech" },
  { Name: "Image Recognition ", Category: "Vision" },
  { Name: "Machine Vision", Category: "Vision" },
];

export const CareerPlaningData = [
  { id: 1, Label: "Career Planning", fill: "Black", branch: "Root" },
  {
    id: 2,
    Label: "Current skills",
    parentId: 1,
    branch: "Right",
    fill: "Blue",
  },
  {
    id: 3,
    Label: "Technical skills",
    parentId: 2,
    branch: "subRight",
  },
  {
    id: 4,
    Label: "Interpersonal skills",
    parentId: 2,
    branch: "subRight",
  },
  { id: 5, Label: "Language", parentId: 2, branch: "subRight" },
  { id: 9, Label: "Computing", parentId: 3, branch: "subRight" },
  {
    id: 10,
    Label: "Chemical engineering",
    parentId: 3,
    branch: "subRight",
  },
  {
    id: 11,
    Label: "Verbal communication",
    parentId: 4,
    branch: "subRight",
  },
  {
    id: 12,
    Label: "Decision making",
    parentId: 4,
    branch: "subRight",
  },
  {
    id: 13,
    Label: "Problem solving",
    parentId: 4,
    branch: "subRight",
  },
  { id: 14, Label: "Negotiating", parentId: 4, branch: "subRight" },
  { id: 15, Label: "English", parentId: 5, branch: "subRight" },
  { id: 16, Label: "Chinese", parentId: 5, branch: "subRight" },
  { id: 22, Label: "Programming", parentId: 9, branch: "subRight" },
  {
    id: 23,
    Label: "Database management",
    parentId: 9,
    branch: "subRight",
  },
  {
    id: 24,
    Label: "Network and Security",
    parentId: 9,
    branch: "subRight",
  },
  {
    id: 25,
    Label: "Software testing",
    parentId: 9,
    branch: "subRight",
  },
  {
    id: 26,
    Label: "HAZOP studies",
    parentId: 10,
    branch: "subRight",
  },
  {
    id: 27,
    Label: "Refinery operations",
    parentId: 10,
    branch: "subRight",
  },
  {
    id: 30,
    Label: "Possibilities",
    parentId: 1,
    branch: "Left",
    fill: "red",
  },
  {
    id: 31,
    Label: "Preferences",
    parentId: 1,
    branch: "Left",
    fill: "lightGreen",
  },
  {
    id: 32,
    Label: "Education",
    parentId: 1,
    branch: "Left",
    fill: "yellow",
  },
  {
    id: 17,
    Label: "Acheive a new position",
    parentId: 30,
    branch: "subLeft",
  },
  {
    id: 18,
    Label: "Improve a current position",
    parentId: 30,
    branch: "subLeft",
  },
  {
    id: 19,
    Label: "Look for a new job",
    parentId: 31,
    branch: "subLeft",
  },
  { id: 20, Label: "College", parentId: 32, branch: "subLeft" },
  { id: 21, Label: "University", parentId: 32, branch: "subLeft" },
  { id: 28, Label: "ABC College", parentId: 20, branch: "subLeft" },
  {
    id: 29,
    Label: "Hello World University",
    parentId: 21,
    branch: "subLeft",
  },
];
export const chiefExecutiveChartData = [
  { Id: "parent", Role: "Chief Executive Officer", color: "yellow" },
  {
    Id: "1",
    Role: "Chief Finance Officer",
    Manager: "parent",
    color: "#a3e4e7",
  },
  {
    Id: "5",
    Role: "Director of Human Resources",
    Manager: "parent",
    color: "#a3e4e7",
  },
  {
    Id: "9",
    Role: "Director of Sales",
    Manager: "parent",
    color: "#a3e4e7",
  },
  {
    Id: "13",
    Role: "Chief Technical Officer",
    Manager: "parent",
    color: "#a3e4e7",
  },
  {
    Id: "17",
    Role: "Director of Marketing",
    Manager: "parent",
    color: "#a3e4e7",
  },
  {
    Id: "2",
    Role: "Financial Strategy",
    Manager: "1",
    color: "#ed96e2",
  },
  {
    Id: "3",
    Role: "Accounts Management",
    Manager: "1",
    color: "#ed96e2",
  },
  {
    Id: "4",
    Role: "Budget and Forecasting",
    Manager: "1",
    color: "#ed96e2",
  },
  {
    Id: "6",
    Role: "Staff Recruitment",
    Manager: "5",
    color: "#40f7ed",
  },
  {
    Id: "7",
    Role: "Staff Development",
    Manager: "5",
    color: "#40f7ed",
  },
  {
    Id: "8",
    Role: "Operation Management",
    Manager: "5",
    color: "#40f7ed",
  },
  {
    Id: "10",
    Role: "Domestic Sales",
    Manager: "9",
    color: "#f1d0f1",
  },
  {
    Id: "11",
    Role: "International Sales",
    Manager: "9",
    color: "#f1d0f1",
  },
  {
    Id: "12",
    Role: "Customer RelationShip Management",
    Manager: "9",
    color: "#f1d0f1",
  },
  {
    Id: "14",
    Role: "infrastructure Management",
    Manager: "13",
    color: "#aba6ab",
  },
  {
    Id: "15",
    Role: "Research and Development",
    Manager: "13",
    color: "#aba6ab",
  },
  {
    Id: "16",
    Role: "Information Management",
    Manager: "13",
    color: "#aba6ab",
  },
];
