export const organizationChartData = [
    { Id: "parent", Role: "Board", color: "#71AF17" },
    {
      Id: "1",
      Role: "General Manager",
      Manager: "parent",
      color: "#71AF17",
    },
    {
      Id: "11",
      Role: "Assistant General Manager",
      Manager: "1",
      color: "#71AF17",
    },
    {
      Id: "2",
      Role: "Human Resource Manager",
      Manager: "1",
      color: "#1859B7",
    },
    { Id: "3", Role: "Trainers", Manager: "2", color: "" },
    { Id: "4", Role: "Recruiting Team", Manager: "2", color: "" },
    { Id: "5", Role: "Finance Asst. Manager", Manager: "2", color: "" },
    {
      Id: "6",
      Role: "Design Manager",
      Manager: "1",
      color: "#1859B7",
    },
    { Id: "7", Role: "Design Supervisor", Manager: "6", color: "" },
    { Id: "8", Role: "Development Supervisor", Manager: "6", color: "" },
    { Id: "9", Role: "Drafting Supervisor", Manager: "6", color: "" },
    {
      Id: "10",
      Role: "Operations Manager",
      Manager: "1",
      color: "#1859B7",
    },
    { Id: "11", Role: "Statistics Department", Manager: "10", color: "" },
    { Id: "12", Role: "Logistics Department", Manager: "10", color: "" },
    {
      Id: "16",
      Role: "Marketing Manager",
      Manager: "1",
      color: "#1859B7",
    },
    { Id: "17", Role: "Overseas Sales Manager", Manager: "16", color: "" },
    { Id: "18", Role: "Petroleum Manager", Manager: "16", color: "" },
    {
      Id: "20",
      Role: "Service Department Manager",
      Manager: "16",
      color: "",
    },
    {
      Id: "21",
      Role: "Quality Control Department",
      Manager: "16",
      color: "",
    },
  ];

  export const chiefExecutiveChartData = [
  { Id: "parent", Role: "Chief Executive Officer", color: "yellow" },
  { Id: "1", Role: "Chief Finance Officer", Manager: "parent", color: "#a3e4e7" },
  { Id: "5", Role: "Director of Human Resources", Manager: "parent", color: "#a3e4e7" },
  { Id: "9", Role: "Director of Sales", Manager: "parent", color: "#a3e4e7" },
  { Id: "13", Role: "Chief Technical Officer", Manager: "parent", color: "#a3e4e7" },
  { Id: "17", Role: "Director of Marketing", Manager: "parent", color: "#a3e4e7" },
  { Id: "2", Role: "Financial Strategy", Manager: "1", color: "#ed96e2" },
  { Id: "3", Role: "Accounts Management", Manager: "1", color: "#ed96e2" },
  { Id: "4", Role: "Budget and Forecasting", Manager: "1", color: "#ed96e2" },
  { Id: "6", Role: "Staff Recruitment", Manager: "5", color: "#40f7ed" },
  { Id: "7", Role: "Staff Development", Manager: "5", color: "#40f7ed" },
  { Id: "8", Role: "Operation Management", Manager: "5", color: "#40f7ed" },
  { Id: "10", Role: "Domestic Sales", Manager: "9", color: "#f1d0f1" },
  { Id: "11", Role: "International Sales", Manager: "9", color: "#f1d0f1" },
  { Id: "12", Role: "Customer RelationShip Management", Manager: "9", color: "#f1d0f1" },
  { Id: "14", Role: "infrastructure Management", Manager: "13", color: "#aba6ab" },
  { Id: "15", Role: "Research and Development", Manager: "13", color: "#aba6ab" },
  { Id: "16", Role: "Information Management", Manager: "13", color: "#aba6ab" }
  ]; 